### ISSUE TITLE
WP-CLI driver: path to WpcliLogger.php is wrong

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#11]
The `--require=src/WpcliLogger.php` path is wrong. It's relative to the root directory of wherever the user run `behat` from.

https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/WpcliLogger.php#L9 needs adapting for this.

Maybe `getcwd` or `dirname(__FILE__)`, not sure

**Comment by paulgibbs** [comment]
@dan-westall The problems you had with the `--require=` path with remote WP-CLi, should be fixed in master now.

**Comment by dan-westall** [comment]
👍 awesome will confirm, if theres any issues i'll report back
