### ISSUE TITLE
behat --init fails

### ISSUE THREAD

**Issue by dseidl** [paulgibbs/behat-wordpress-extension#110]
Do I have to install another mink2selenium Driver package?

After following your installation docs i wanted to run behat --init.

Output:
[RuntimeException]                                             
Install MinkSelenium2Driver in order to use selenium2 driver. 

Do i have to install this package? 
composer require behat/mink-selenium2-driver

If so, add it to your docs please.

And a example test would be awesome too there.

## Your environment
* Version used: 0.7.0
* PHP 7.1
* Ubuntu

**Comment by paulgibbs** [comment]
@stephenharris Our behat.yml.dist references selenium2, and since we moved `behat/mink-selenium2-driver` out of Composer's `require` into `require-dev` a month back, the above happens on a new checkout. What do you think we should do?

@dseidl Sorry about that. You're right, you would need to use `behat/mink-selenium2-driver` unless you took the Selenium references out of your behat.yml (which I acknowledge might be hard if you have not used Behat before).

This won't help you much right now but be assured documentation is important to us and we have a plan to improve it, and the first improvements to the website should go live in a week or two.

**Comment by dseidl** [comment]
@paulgibbs glad to hear!

the project looks really promising. especially if you are new to testing.
Ill dive more in the ecosystem of behat and your extension. Maybe i then can provide a little help in improving the documentation.

Just a little question:
I've got things up and running, and figured out the db changes are persisting in my "main" db. Now the Config database.restore_after_test seems not to be working.
`database:
  restore_after_test: false`
Output:
`Unrecognized option "database" under "testwork.wordpress"`

Is the documentation there also out of date or could it be another problem?  Furthermore it would be awesome if you can provide whole new db credentials to run the tests for.

**Comment by stephenharris** [comment]
@paulgibbs  I think we should provide an example `composer.json` which `require-devs` Behat, WordHat, and the Selenium and Goutte drivers. That will provide an easy 'quick start' for users.

**Comment by paulgibbs** [comment]
@stephenharris my initial reaction to that is i'm fine with forcing people to learn about how to use Composer (a win-win), as long as our docs give step-by-step.

I do think whatever we have in the behat.yml.dist file needs to work with whatever we tell people to install via Composer in the docs, obviously, which apparently isn't what we're doing right now. :p

**Comment by paulgibbs** [comment]
@dseidl If you can upload the contents of your config file somewhere, i'll check it tomorrow. Remember to obscure any passwords/sensitive information/etc that you might have added.

The restore_after_test feature is so new, the frying pan is still hot, and you need to be running `dev-master` of WordHat for it to work. If you're using 0.7 (the latest versioned release), it won't work.

**Comment by dseidl** [comment]
@paulgibbs thank you. that already answered my question. (I'm using latest release bec of #109 )Everything i tried worked, except of that. In future the docs at wordhat.info should always be on the latest release.

**Comment by stephenharris** [comment]
@paulgibbs - absolutely. So a minimal and valid composer.json they can copy and paste would be ideal. Developers familiar with composer will know what to do anyway and just need the package names.

**Comment by paulgibbs** [comment]
@stephenharris I meant, I'm happy to continue requiring people to type the Composer commands on the CLI. Even only junior developers with WordPress PHP experience. :)

I've not seen or (can find via a quick Google) other Composer packages that offer a sample Composer.json either.

**Comment by paulgibbs** [comment]
@dseidl You're right. This is the first time we've run into problems with the documentation not being versioned to a specific release. I'm going to open a new ticket to investigate this but, assuming no extra contributors, will probably take weeks/month before I get around to looking at it.

**Comment by paulgibbs** [comment]
@stephenharris Are you OK with me adding the Selenium package into the tutorial installation docs on the website? Or do you want me to update the behat.yml.dist and remove references to Selenium (meaning  if someone wanted to test JS, we'd explain how to configure Behat.yml in a FAQ page or something?)

**Comment by dseidl** [comment]
@paulgibbs well on what basis u removed the `behat/mink-selenium2-driver` package to `require-devs`? If you want to keep that i would definitely remove selenium from the preset behat config. And for completion write that up how u can get selenium tests up and running. (by installing `behat/mink-selenium2-driver` & config example)

If you are fine with it i would love to write something up and create a pr for that.
Furthermore as a vvv user how to get selenium running on your host machine out of the vagrant box. and/or how to run the tests in the box from your host via wpcli.

**Comment by paulgibbs** [comment]
It got moved in #71 and we forgot to update the installation docs at that point.

Give me another week or so to structure the website a bit more and then I'll be happy to accept doc contributions (I wouldn't want you to waste your time just yet!).

**Comment by paulgibbs** [comment]
In the new docs i'm drafting, i've decided to get the selenium driver installed (since we already get the Goutte driver installed, might as well get something for JS installed too). Subject to change of course
