### ISSUE TITLE
WPCLI driver fails on stderr output

### ISSUE THREAD

**Issue by ataylorme** [paulgibbs/behat-wordpress-extension#111]
## Expected behavior
I expect notices given from wpcli to not cause a failure when using the wpcli driver for WordHat.

## Current behavior
Any `stderr` output causes a failure (see [src/Driver/WpcliDriver.php line 138](https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/Driver/WpcliDriver.php#L138)). Despite the name `stderr` is just another output stream and programs pass notices, help tips and other information to `stderr` that shouldn't cause a failure. 

## Possible solution
Failures should be determined by status code, not `stderr` output. Additionally throw a warning with the `stderr` output rather than causing a failure.

## Steps to reproduce (for bugs)
1. Run the wpcli command `plugin list`
2. wpcli returns `Error: 'plugins' is not a registered wp command. See 'wp help'.
Did you mean 'plugin'?` in `stderr`

## Context
Specifically I'm attempting to run the wpcli driver in conjunction with Pantheon's command line tool [Terminus](https://pantheon.io/docs/terminus/). Pantheon does not provide direct SSH access but Terminus can run wpcli commands on a remote site.

The use case is Behat tests as part of a CI process against a site on Pantheon so that I am testing on the production infrastructure rather than testing in a WordPress install on CI.

Terminus uses `stderr` to give warning messages about site status, which cause the driver to fail, while the commands succeed and give a `0` status code.

## Your environment
* Version used: `dev-master`
* PHP 7.1 on CircleCI `1.x`

**Comment by paulgibbs** [comment]
I think this is a strange use of `stderr`, but there we go. This part of the code has already gone through several revisions (see #40).

Before this can be changed, we'd need to verify that each WP-CLI command we can make with the WP-CLI driver returns an appropriate status code for any error states.

**Comment by ataylorme** [comment]
Thanks for the comments @paulgibbs 

I've taken a first stab at this and checked the following commands:
* [`core is-installed`](https://github.com/wp-cli/core-command/blob/master/src/Core_Command.php#L294:L307) returns `0` if WordPress is installed and `1` if it is not, accounting for multisite.
* [`cache flush`](https://github.com/wp-cli/cache-command/blob/master/src/Cache_Command.php#L152:L160) while not returning a status code directly it returns [`WP_CLI::error`](https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L723:L741) which returns an error code of `1` for errors.

It's not an exhaustive list but I imagine all commands follow this pattern and return a status code.

I also found instances such as [`plugin activate`](https://github.com/wp-cli/extension-command/blob/master/src/Plugin_Command.php#L275) that will [return a warning using `stderr`](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Loggers/Execution.php#L43:L45). In this case there will be a warning when trying to activate a plugin that's already active. I don't think a test should fail if a warning like this occurs in `stdout`.

**Comment by ataylorme** [comment]
> It's not an exhaustive list

When I have more time I can work on tracking down all the commands used by the wpcli driver

**Comment by danielbachhuber** [comment]
Just to weigh in here, some commands do have error codes but others don't. It really depends on whether you'd _expect_ the command to use an error code vs. not.

For instance, `wp post list --meta_key=foo` wouldn't have an error code even if there weren't matching results. But `wp core download` could return an error code if any part of the process failed.

**Comment by ataylorme** [comment]
This sounds reasonable to me as reading just the error codes to determine when WordHat fails will result in wpcli failures causing WordHat failures but only warnings allow tests to keep going.

With something like `wp post list` if no posts are returned the Behat test should check the expected results and fail if we don't get back what's expected.

**Comment by paulgibbs** [comment]
I've reviewed all the commands we use and while this change means error detection isn't as robust as I'd prefer, i'm happy for us to do in the name of compatibility with other services.

**Comment by paulgibbs** [comment]
PR merged in!
