### ISSUE TITLE
Friendlier message when WordPress core is not installed

### ISSUE THREAD

**Issue by ataylorme** [paulgibbs/behat-wordpress-extension#112]
## Expected behavior
The wpcli driver for WordHat provides a friendlier, more useful message when WordPress core is not installed.

## Current behavior
The current error message leads me to believe the `path` is wrong when wpcli can actually find WordPress, it's just not installed.

## Possible solution
Update the error message to indicate WordPress is not installed rather than not found.

## Steps to reproduce (for bugs)
1. Run WordHat with the wpcli driver against a WordPress site that hasn't been installed

## Context
The error message was a bit misleading and I didn't realize the issue was WordPress was not installed until I viewed the driver code.

I was attempting to write a custom test using WordHat scenarios that installed WordPress first, then ran more tests. My initial test would always fail.

**Comment by paulgibbs** [comment]
Great idea. Thank you very much for the PR, it's been merged in.
