### ISSUE TITLE
The wpcli driver requires a full path and doesn't support relative paths for wpcli

### ISSUE THREAD

**Issue by ataylorme** [paulgibbs/behat-wordpress-extension#114]
The wpcli driver requires WordPress to be present locally but this breaks down when using wpcli via ssh to run tests on a site located elsewhere.

## Expected behavior
`path` defined in the `PaulGibbs\WordpressBehatExtension` section of `behat.yml` is send to wpcli even when the directory does not exist locally.

## Current behavior
Path is stripped if WordPress core does not exist locally.

## Possible solution
Remove the `realpath` wrapper around path in the wpcli driver.

## Context
I'm attempting to run WordHat tests on a site hosted elsewhere (tests on CircleCI, site in staging) using the wpcli driver. I can connect via ssh and wpcli but the path variable is stripped as I don't have a copy of WordPress core locally.

Path is necessary on the remote machine as WordPress core is in the `wp` subdirectory.

**Comment by stephenharris** [comment]
+1 I discussed this with @paulgibbs at WCEU. For me it was not such a problem for me though. I passed the path of the remote install in the wp-cli alias config and I had a 'dummy' WordPress install to satisfy WordHat's path requirements

**Comment by paulgibbs** [comment]
For local dev, I use the WPCLI driver over SSH (into a VM). My `path` is `/vagrant/wp` which refers to the WordPress folder on the VM (the path does not exist on the host computer).

**Comment by ataylorme** [comment]
> My path is /vagrant/wp which refers to the WordPress folder on the VM (the path does not exist on the host computer).

This is fine when the full path is known. In my case the site I'm testing is a container based staging environment (not a local VM) and the full path is unknown as it contains a container ID, which may change.

I would like to be able to pass a relative path such as `wp`, which is different than the full path `/vagrant/wp` you are using.

[`realpath`](http://php.net/manual/en/function.realpath.php) looks for an absolute path. Since I've passed a relative path it returns `false`, in turn making the path empty.

When I comment out `$this->path  = realpath($path);` in the driver the relative path works fine. Since wpcli supports relative paths in the `--path` argument it would be nice if WordHat supported them as well.

**Comment by paulgibbs** [comment]
That's a good reason and a use case I hadn't considered. We can make that change.

**Comment by paulgibbs** [comment]
This is fixed now. Thanks for the feedback, very useful!
