### ISSUE TITLE
Copy sample behat config file via Composer

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#117]
Our install instructions say "copy behat.yml.dist" into your project folder, etc, as a quick-start for Behat. We can do this automagically via Composer's scripts.post-install-cmd section. 

https://github.com/solsoft/wordpress-boilerplate/blob/4.x/composer.json for inspiration

**Comment by paulgibbs** [comment]
Only works for root packages.

See https://github.com/composer/composer/issues/1193

**Comment by stevector** [comment]
I haven't used it yet, but I think Symfony Flex is meant to solve this problem space of extra file set up: https://symfony.com/doc/current/setup/flex.html

**Comment by paulgibbs** [comment]
That's interesting. As Flex itself is a Composer package, I think we'd have to require end-users to 1) use composer for their testing projects (we already sort of do), and 2) install symphony flex before wordhat.

I couldn't find a clear answer if Flex in a root package will work for the `require` dependencies.
we would need to add a wordhat thingy to https://github.com/symfony/recipes-contrib and I don't know how policed that repo is and how up they are for outside contributions. seem it could end up being a huge giant repo if this catches on, unless they're only supporting popular packages.

**Comment by paulgibbs** [comment]
I guess for point 1 I am thinking of this wrong, because we'd hook the script to the name of the WordHat project, so it would work there.

**Comment by paulgibbs** [comment]
I've found a post from the Symfony author who said that basically anything goes for the contrib repo, so I think this is worth spending time on (plus, it's interesting!).

**Comment by paulgibbs** [comment]
Notes:

* http://fabien.potencier.org/symfony4-contributing-recipes.html is very useful.
* We would use `copy-from-package` in the recipe but otherwise similar to https://github.com/symfony/recipes-contrib/blob/master/orbitale/cms-bundle/3.0/manifest.json.
* https://github.com/symfony/recipes explains the format.

**Comment by paulgibbs** [comment]
Crap. After learning more about this and just about finishing it, I see this in the requirements: "The package must have an MIT or BSD license;"

WordHat is GPLv3+. 😳
