### ISSUE TITLE
Notice thrown when specifying a user

### ISSUE THREAD

**Issue by rvodden** [paulgibbs/behat-wordpress-extension#126]
If i specify that a user should exist as part of a feature, then the following notice is displayed, which causes the step to fail, even though the user is created successfully.

```
Notice: Undefined property: stdClass::$user_nicename in vendor/paulgibbs/behat-wordpress-extension/src/Context/RawWordpressContext.php line 412
```

## Expected behavior
Using the step `Given there are users` creates the appropriate users without error.
## Current Behaviour
Using this step causes this error:
`Notice: Undefined property: stdClass::$user_nicename in vendor/paulgibbs/behat-wordpress-extension/src/Context/RawWordpressContext.php line 412`
## Possible solution
The function which creates the user returns an array which contains user_nicename:
```
    public function createUser($user_login, $user_email, $args = [])
    {
        $args['user_email'] = $user_email;
        $args['user_login'] = $user_login;

        $user = $this->getDriver()->user->create($args);

        return array(
            'id'   => $user->ID,
            'slug' => $user->user_nicename,
        );
    }
```
`user_nicename` is an optional field, however, so better might be:
```
    public function createUser($user_login, $user_email, $args = [])
    {
        $args['user_email'] = $user_email;
        $args['user_login'] = $user_login;

        $user = $this->getDriver()->user->create($args);

        return array(
            'id'   => $user->ID,
            'slug' => $user->user_login,
        );
    }
```
## Steps to reproduce (for bugs)
1. Execute this feature file:
```
Feature: Administration
	In order that the displayed admin page is accurate
	As a website administrator
	I need to be able to see the pages button on the menu

Background:
    Given there are users:
    | user_login | user_pass |  user_email        | role          |
    | admin      | admin     |  admin@example.com | administrator |

Scenario: Navigate to the pages screen
Given I am logged in as an admin
And I am on the dashboard
When I click on the pages link in the header
Then I should be on the pages page
```
2. Observe this output:
```
Feature: Administration
  In order that the displayed admin page is accurate
  As a website administrator
  I need to be able to see the pages button on the menu

  Background:              # features/BugReplication.feature:6
    Given there are users: # PaulGibbs\WordpressBehatExtension\Context\UserContext::thereAreUsers()
      | user_login | user_pass | user_email        | role          |
      | admin      | admin     | admin@example.com | administrator |
      Notice: Undefined property: stdClass::$user_nicename in vendor/paulgibbs/behat-wordpress-extension/src/Context/RawWordpressContext.php line 412

  Scenario: Navigate to the pages screen         # features/BugReplication.feature:11
    Given I am logged in as an admin             # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
    And I am on the dashboard                    # PaulGibbs\WordpressBehatExtension\Context\DashboardContext::iAmOnDashboard()
    When I click on the pages link in the header # PaulGibbs\WordpressBehatExtension\Context\DashboardContext::iClickOnHeaderLink()
    Then I should be on the pages page           # PaulGibbs\WordpressBehatExtension\Context\DashboardContext::iShouldBeOnThePage()

--- Failed scenarios:

    features/BugReplication.feature:11

1 scenario (1 failed)
5 steps (1 failed, 4 skipped)
0m1.26s (14.45Mb)
```
## Context
I'm writing a plugin which creates a post type, and was trying to check that the new post type appears on the menu.
## Your environment
* Version used: 
dev-master
* Environment name and version (e.g. PHP 7.1 on nginx 1.11.9):
php 7.0.22 on apache 2.4
* Server operating system type and version:
MacOS

**Comment by paulgibbs** [comment]
@rvodden Are you using the WP-CLI or the WP-PHP (formerly known as "WP-API") driver? If you don't know what this is or haven't explicitly set one in your behat.yml, you're using WP-CLI. :)

**Comment by paulgibbs** [comment]
I suspect this is a bug. We intend for the entire set of public properties from a `WP_User` object to be returned. Once we know what driver is used, I'll see what's going on.

**Comment by rvodden** [comment]
It actually affects both drivers; I was using the WPCLI driver as it happens, but then your nicely set up CI chain meant I have to fix it for both 👍

**Comment by paulgibbs** [comment]
I'm moving house next week and might be internet-less for the week after, but I'll get this figured as soon as I can.

**Comment by rvodden** [comment]
No rush :) Good luck with the move!

**Comment by paulgibbs** [comment]
From your sample feature, it found a duplicate step definition (so I removed one in 0dbc73a41d4cb8217c63f19a1a5d835595e25c2a) which was unexpected, and in 0dbc73a41d4cb8217c63f19a1a5d835595e25c2a I update the WP-CLI driver to return more properties, including `user_nicename`.

(I am aware we need to write more features to test functionality that already exists; that's probably the last big thing before v1.0).

I don't think the WP-PHP has exactly the same issue (it should return a `WP_User` object internally, so it has `user_nicename` already). I haven't tested it yet, though.

**Comment by rvodden** [comment]
Hey - sorry for the slow reply. the fix you've put on `fix-126` works briliantly for WPCLI. I've taken a sneaky look at WPPHP too and you're right - the problem isn't the same. The problem is the combination of line 24:

    $user = wp_insert_user($args);`

and line 30:

    return $this->get($user->ID);

in `src\Driver\Element\Wpphp\UserElement.php`. `wp_insert_user` either returns an `int` or a `WP_Error` so the `$user->ID` on line 30 is giving an `Undefined propery` error. If line 30 is replaced with:

    return $this->get($user);

then all works well.

**Comment by paulgibbs** [comment]
Nice find!
