### ISSUE TITLE
Docs: Include some keywords in the wordhat.info site title

### ISSUE THREAD

**Issue by johnbillion** [paulgibbs/behat-wordpress-extension#137]
Googling for something along the lines of "WordPress Behat" results in WordHat being quite far down the results. Changing the title of the wordhat.info site to something like `WordHat - Behat for WordPress` would improve discoverability.

**Comment by paulgibbs** [comment]
Can we hire you as an SEO consultant

**Comment by paulgibbs** [comment]
More seriously, i’ll take a look at the first page of results and see what I can take from there.  I think it’s going to be a struggle to rank first because the wordhat site won’t have blog posts etc but I agree first page would be the goal.

**Comment by paulgibbs** [comment]
Site `<title>` changed in #138. I also tweaked the menu style on desktop-width browsers because I saw the feature in the Mkdocs changelog and it seems like it will definitely help WordHat once it gets more detailed document.
