### ISSUE TITLE
Improve CodeSniffer sniffs

### ISSUE THREAD

**Issue by rvodden** [paulgibbs/behat-wordpress-extension#147]
## Expected behaviour

The BWE convention is that method arguments are in snake case but this currently isn't enforced. There may be other things we'd like CodeSniffer to do - particularly around whitespace - in which case lets use this issue to keep track of them. Where there's a collection I'll go on a CodeSniffer coding spree!

**Comment by paulgibbs** [comment]
This might be more CI-specific, but, something else that shows up in the static analysis tools is the spacing after logical operators. E.g

“! $var” or “&& (! $var)” = what we want
“!$var” or “&& (!$var)” = what Scrutinizer currently insists on

**Comment by rvodden** [comment]
I agree that getting Scrutinizer and phpcs to check the same ruleset would be great :)

**Comment by paulgibbs** [comment]
Scrutinizer and Codacy find different things. I'm least fond of Scrutinizer.

I do have a branch locally? where I experimented with https://github.com/phpstan/phpstan which is an alternative to running these in the cloud.

**Comment by rvodden** [comment]
I'd quite like to turn these on - I think it would help keep phpdoc consistent. It throws a LOT of errors right now tho!!

    <rule ref="Squiz.Commenting.FunctionComment" />
    <rule ref="Squiz.Commenting.FunctionCommentThrowTag" />
    <rule ref="Squiz.Commenting.ClassComment" />
    <rule ref="Squiz.Commenting.VariableComment" />

**Comment by paulgibbs** [comment]
Give us an example what each of those do, and we’ll see. 😀

**Comment by paulgibbs** [comment]
To update old ticket: Scrutinzer was abandoned sometime ago. We use codacy but the config is pretty loose. I'd like to eventually have the project rely on phpcs and phpstan 100% locally.

I tested the four squiz rules proposed above, and added one. "FunctionComment" et al has this annoying quirk where it replaces `@param bool $foo bar` with `@param boolean $foo bar` and this seems over-opiniated and verbose to me. There's no way of controlling the behaviour for that, unfortunately.
