### ISSUE TITLE
Improve feature test coverage.

### ISSUE THREAD

**Issue by rvodden** [paulgibbs/behat-wordpress-extension#149]
There are parts of the driver API not exercised by the feature tests. This will help prevent issues like #145 and mean we've got examples of usage for all the steps we've implemented.

**Comment by paulgibbs** [comment]
I have a spreadsheet somewhere with a list of features-to-write. I’ll move it here later.

**Comment by paulgibbs** [comment]
Here we go: https://docs.google.com/spreadsheets/d/1CDPtdHUZS7enoCl-jo4yCFL5eBPDc9shGIKApJgnlRo/edit?usp=sharing

**Comment by paulgibbs** [comment]
I am working on this

**Comment by paulgibbs** [comment]
This is quite close to being done and is going OK so far.

**Comment by paulgibbs** [comment]
Done! We're good.
