### ISSUE TITLE
Improvement: Ability to pass a redirect_to when using the login method

### ISSUE THREAD

**Issue by dan-westall** [paulgibbs/behat-wordpress-extension#15]
Having the ability to optionally ability to set ```redirect_to``` when using ```iAmLoggedInAs``` would reduce scenario run time.

**Comment by paulgibbs** [comment]
Do you meant the function, or also its step definition? If the latter, my initial reaction is that I am unconvinced that you couldn't/shouldn't use do something like this:

`Given I am logged in as Yoda
And when I go to some page
When I do something
Then something happens`

You could also put the log-in into a Background: http://behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds

**Comment by dan-westall** [comment]
Theres no way for me to reuse the login method and pass a redirect url. I would need to recreate a completely new `logIn()` method. For example if i wanted to create a single step definition `I login as a admin and go to customizer` while they are currently 2 different steps, this can add considerable time to a Scenario. Being able to pass a redirect method would allow me to use existing functionality provided by either `iAmLoggedInAs` or `logIn` without reinventing wheels.

**Comment by paulgibbs** [comment]
We can change the function to support this, sure. I don't think we'll support this in our built-in step definitions, but let's give people the flexibility to craft their own if they want to do this.

**Comment by paulgibbs** [comment]
Looking again, this issue was created pre-driverisation so i'll add the param in there.
