### ISSUE TITLE
Implement validate credentials for WPCLI driver

### ISSUE THREAD

**Issue by rvodden** [paulgibbs/behat-wordpress-extension#155]
At present the `validateCredentials` method in the `UserElement` of the WPCLI driver throws an `UnsupportedDriverException` it would be great to find a way to implement this method in line with the WPPHP driver.

**Comment by paulgibbs** [comment]
I've decided I do not like behaviour that cannot be specific to all drivers, unless there is a strong reason, and I do not think this has it. I have been skeptical of the benefit of trying to compare user passwords in this method, so I am going to rip it out.
