### ISSUE TITLE
Invalid yml in driver files

### ISSUE THREAD

**Issue by ataylorme** [paulgibbs/behat-wordpress-extension#166]
The yml in `src/ServiceContainer/config/services.yml` is not valid. I'm using Bheat version `3.4.3` and WordHat version `0.9.0`

## Expected behaviour
I expect the yml to validate and Behat to pass

## Current behaviour
Behat to fail due to invalid yml in the WordHat source.

## Possible solution
Quote the line `%wordpress.parameters%`

## Steps to reproduce (for bugs)
See [this failing build](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/1289) on Circle CI

## Context
I'm testing pull request on GitHub by deploying them to a new environment, cloning WordPress database and uploads from the live site then running Behat/WordHat tests against the environment with the wp-cli driver.

## Your environment
PHP `7.1` and Nginx.

**Comment by paulgibbs** [comment]
Thanks for reporting this and providing a fix!

**Comment by ataylorme** [comment]
No worries - not sure how your tests are run but I run Behat is strict mode (`--strict`) and that's how I was able to catch it.

**Comment by paulgibbs** [comment]
0.9.1's just been released

**Comment by ataylorme** [comment]
Seems this is happening in other driver files as well. I'll open a new PR.

**Comment by paulgibbs** [comment]
Can you validate *all* the YML files please?

**Comment by ataylorme** [comment]
Yes, I'll also see about running the WordHat tests in strict mode so we can catch issues in the future

**Comment by ataylorme** [comment]
@paulgibbs this has been updated in #168. Not sure what the best way to proceed is - either tagging a new version or re-tagging `0.9.1`. Either way let me know if there is anything else I can do

**Comment by paulgibbs** [comment]
I'lll tag a 0.9.2 this weekend sometime :)

**Comment by paulgibbs** [comment]
I'm doing this now.
