### ISSUE TITLE
iAmViewingAuthorArchive() is accepting username as a parameter instead of role name.

### ISSUE THREAD

**Issue by dealancer** [paulgibbs/behat-wordpress-extension#183]
Most of the contexts are accepting role as a parameters, but iAmViewingAuthorArchive() is accepting username instead. It is inconsistent and makes some tests to fall.

## Expected behaviour
This function should accept user role parameter, instead of the user name. It should also get a user for a given role.

## Current behavior
When using admin role in test, test is falling, because it treats role as username:

```
    When I am viewing posts published by admin # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmViewingAuthorArchive()
      WP-CLI driver failure in method get():
      .
      Tried to run: wp --path='/var/www/docroot' --url='http://guwordpress.docksal' --no-color user get admin --format=json --fields='ID,user_login,display_name,user_email,user_registered,roles,user_pass,user_nicename,user_url,user_activation_key,user_status,url'
      (1) (UnexpectedValueException)
```

## Possible solution

```
/**
 * Go to a user's author archive page.
 *
 * Example: Given I am viewing posts published by admin
 * Example: When I am viewing posts published by admin
 *
 * @When I am viewing posts published by :user
 *
 * @param string $role
 */
public function iAmViewingAuthorArchive($role)
{
    $role  = strtolower($role);
    $users = $this->getWordpressParameter('users');

    if ($users === null || empty($users[$role])) {
        throw new RuntimeException("User details for role \"{$role}\" not found.");
    }

    $this->visitPath(sprintf(
        $this->getWordpressParameters()['permalinks']['author_archive'],
        $this->getUserDataFromUsername('user_nicename', $users[$role]['username'])
    ));
}
```

## Steps to reproduce (for bugs)
1. Admin username should be different from `admin`
2. Run behat

**Comment by paulgibbs** [comment]
Thank you for trying Behat, and for opening this issue and the pull request. I am busy this week, but I will either take time to assess the issue this weekend or on Wednesday next week, and I'll reply here then.

**Comment by paulgibbs** [comment]
I think you're right, and I like your PR.

I'll likely merge it in directly soon, and adjust the "When" to support "published by admin" as well as "published by an admin".

**Comment by dealancer** [comment]
cool, thanks!

**Comment by paulgibbs** [comment]
37a6cf868572f92d8fce050b8b3006774fb5612d

**Comment by paulgibbs** [comment]
This is fixed now. Thanks again @dealancer!
