### ISSUE TITLE
wp-cli path required

### ISSUE THREAD

**Issue by ataylorme** [paulgibbs/behat-wordpress-extension#185]
## Background
I am attempting to run WordHat with the wp-cli driver over SSH against a remote installation to perform QA as part of a deployment process. My process runs on CircleCI and can connect fine but [WordHat requires a path for the wp-cli driver](https://github.com/paulgibbs/behat-wordpress-extension/blob/7ea087d0a610f622cf81a091aec4af0b787ffe59/src/ServiceContainer/WordpressBehatExtension.php#L253:L255).

## Current behaviour
Relative paths are allowed. However, when I use `.`, as WordPress is in the current directory when running wp-cli over SSH, the directory used is the current directory on my continuous integration server due to [path being run through `realpath`](https://github.com/paulgibbs/behat-wordpress-extension/blob/7ea087d0a610f622cf81a091aec4af0b787ffe59/src/Driver/WpcliDriver.php#L53).

I do not know the path on the remote server as there are multiple containers and the paths are dynamic based on which container is being connected to.

## Possible solution
wp-cli lists path as an [optional global parameter](https://make.wordpress.org/cli/handbook/config/#global-parameters) that defaults to `null`. I would like to either remove it from being required by WordHat or allow a value of `null`.

## Steps to reproduce (for bugs)
1. [Example error with path set to `.`](https://circleci.com/gh/ataylorme/wordpress-at-scale-auto-update/19336)
2. [Example error with path set to `null`](https://circleci.com/gh/ataylorme/wordpress-at-scale-auto-update/19350)

**Comment by paulgibbs** [comment]
Hi again @ataylorme, thanks for reporting another configuration quirk. :)

I need to remember why `realpath` is used, or why I insisted that `--path` is set, but it looks like removing `readpath` might be a fix.

It's possible using a WP-CLI alias with WordHat might give you a temporary workaround.

I won't have time to look into this until the weekend or next Wednesday, but I will try to by then, and update you here with my thoughts.

**Comment by ataylorme** [comment]
> it looks like removing `readpath` might be a fix.

I don't see `readpath` anywhere. Do you mean `realpath`?

**Comment by paulgibbs** [comment]
Yeah - autocorrect!

--- 
Paul Gibbs

**Comment by ataylorme** [comment]
@paulgibbs that seemed to do it. See [`src/ServiceContainer/WordpressBehatExtension.php`](https://github.com/ataylorme/behat-wordpress-extension/blob/allow-null-wp-cli-path/src/ServiceContainer/WordpressBehatExtension.php#L254:L258) and [`src/Driver/WpcliDriver.php`](https://github.com/ataylorme/behat-wordpress-extension/blob/allow-null-wp-cli-path/src/Driver/WpcliDriver.php#L54) in my fork.

I commented out WordHat complaining that `path` isn't set and made the default, if no `path` is passed to `null`, which wp-cli allows.

My tests are now getting a different error (below) which I haven't had time to dive into.
```
Given I am logged in as an admin       # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
      Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
```

**Comment by ataylorme** [comment]
Looks like without `path` Behat is having issues finding my login page.

**Comment by paulgibbs** [comment]
@ataylorme  Can you try the branch https://github.com/paulgibbs/behat-wordpress-extension/pull/188 when you have a moment, and let me know if it works for you?

**Comment by ataylorme** [comment]
Still getting _WP-CLI driver requires an `alias` or root `path` set._ ([build log](https://circleci.com/gh/ataylorme/wordpress-at-scale-auto-update/19539)). From [`src/ServiceContainer/WordpressBehatExtension.php`](https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/ServiceContainer/WordpressBehatExtension.php#L255)

**Comment by paulgibbs** [comment]
Whoops! I've just removed that from the branch.

**Comment by ataylorme** [comment]
@paulgibbs got farther along this time but still ran into `Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)` on the `Given I am logged in as an admin` step. More details in [the build log](https://circleci.com/gh/ataylorme/wordpress-at-scale-auto-update/19557).

Basically, I am trying to run WordHat with the wp-cli driver and ssh against a remote site to see if checks pass after updating WordPress plugins. If the tests pass then I deploy the update to production. Previously this was working for me in other projects because I had a copy of WordPress on CircleCI that I used to fake WordHat out. This time I don't have such a copy.

**Comment by paulgibbs** [comment]
That error looks more like something I see if I run an “@javascript” test with Goutte (or another driver that does not run JavaScript).

Or if Selenium or the web browser are different versions (is Selenium updated?).

The log in step is known to cause issues with Selenium (and maybe more); normally though, that sort of failure involves the username or password not being entered, rather than a missing page element causing a fatal error. 

Might any of these ideas apply to your situation?
Otherwise, I’d suggest viewing the actual browser session (over Vnc or another kind of remote connection), because I can’t yet see how thus branch would cause this sort of problem.

**Comment by ataylorme** [comment]
@paulgibbs I figured it out. I was programmatically passing in `site_url` and the value was incorrect. My guess is Behat never hit the correct login screen. 

Things are working well now and the PR to remove making `path` required looks good! Thank you for making the update

**Comment by paulgibbs** [comment]
🛳
