### ISSUE TITLE
Missing xxd

### ISSUE THREAD

**Issue by amwhalen** [paulgibbs/behat-wordpress-extension#19]
While attempting to run some Behat tests using WordHat inside docker images (specifically for use in GitLab CI, but this would apply to any CI system), I ran into errors like:

```
WP-CLI driver query failure: sh: 1: xxd: not found
WP-CLI driver SSH bad checksum.
WP-CLI 1.0.0 (UnexpectedValueException)
```

It appears that many of the PHP-based docker images are built on top of the base `debian:jessie` docker image, for example: `php:5.6` and `wordpress:4.7-php5.6-apache` are both reliant on debian jessie. The debian image unfortunately does not come with `xxd` installed, so I'm seeing those error messages when trying to use those images without modification to run my behat tests.

The `xxd` command is used as part of the code to download the custom WP-CLI logger: https://github.com/paulgibbs/behat-wordpress-extension/blob/95a5e7610e507c483255e6ab0f3b0b50c1c38f41/src/WpcliLogger.php#L18

As a workaround, I'm able to install `xxd` using a customized Dockerfile and adding a step to run `apt-get install vim-common`. Another option would be to add a step in the CI tool configuration to run the `apt-get install vim-common` every time the tests are run.

Perhaps there's a more reliable way to download the additional library? If not, others will likely run across the same errors and I figured I'd document some possible workarounds.

**Comment by paulgibbs** [comment]
That's unfortunate. I'll have to figure out an alternate approach for that; any ideas welcome. Thanks for letting me know.

Having openssl output as binary was to workaround a quirk described thus: http://unix.stackexchange.com/questions/42797/openssl-dgst-sha1-producing-an-extraneous-stdin-prefix-and-trailing-new

I don't want to use sha1sum (etc) because it's called different on Mac and Linux, and earlier versions attempted to detect which one was installed, but what I ended up with was significantly simpler.

**Comment by paulgibbs** [comment]
@amwhalen Looking at that page I linked to, someone provided an example that uses `sed`, like so:

> echo -n "foo" | openssl dgst -sha1 | sed 's/^.* //'

Does `debian:jessie` have `sed` pre-installed?

**Comment by amwhalen** [comment]
It does have sed, and that should work in this specific case. It appears that the sed option works on a Mac too (there's always some difference between the sed on Mac and on Unix/Linux). The base image actually doesn't have curl or openssl installed, but the PHP images based on jessie appear to install those when they add curl and ssl support into PHP. So the sed fix should work for a majority. Obviously won't work on Windows, and I'm not sure if it'll work on other PHP images not based on jessie, such as those built on top of alpine.

**Comment by paulgibbs** [comment]
WordHat has a requirement for CURL somewhere (or maybe it's one of its dependencies), so I feel happy to rely on that.
