### ISSUE TITLE
 Unexpected alert open error

### ISSUE THREAD

**Issue by dealancer** [paulgibbs/behat-wordpress-extension#211]
## Expected behaviour

Alert should be ignored.

## Current behavour

Test fails, no screenshots are made.

## Possible solution

https://stackoverflow.com/questions/39646444/how-to-handle-a-javascript-alert-window-using-php-behat-mink-selenium2-chrome-we

## Steps to reproduce (for bugs)

Not sure if there are reliable way to reproduce it.

## Context

This happens after log in to WP website.

## Your environment

Docksal dev environment.

**Comment by paulgibbs** [comment]
Why does your WordPress throw `alert()` when you log in?

**Comment by dealancer** [comment]
I have no idea, it happens randomly, I was not able manually reproduce this issue.

**Comment by paulgibbs** [comment]
If you run it in a browser (not headless, so you can see what's going on), what's the content of the alert message, or is it blank?

**Comment by paulgibbs** [comment]
I'm going to close this because I think something custom is throwing Javascript alerts, and I have no guess at why WordHat might be causing one. We can re-open if we have ideas to track it down more.
