### ISSUE TITLE
Unnecessary dependency to jQuery might cause errors

### ISSUE THREAD

**Issue by uuf6429** [paulgibbs/behat-wordpress-extension#213]
In some places ([Toolbar.php:122](https://github.com/paulgibbs/behat-wordpress-extension/blob/05d4262c9ff4fbaee3ca3fe0048b09d99be19161/src/PageObject/Element/Toolbar.php#L122) and [Toolbar.php:188](https://github.com/paulgibbs/behat-wordpress-extension/blob/05d4262c9ff4fbaee3ca3fe0048b09d99be19161/src/PageObject/Element/Toolbar.php#L188)), jQuery is used to add a classname (`hover`) to an element.

## Expected behaviour
If the element is missing or for some reason jQuery is not loaded, this should degrade gracefully. In particular, I don't think it should expect or depend on jQuery.
I would expect an error similar to element not found or so.

## Current behaviour
If for some reason the current page does not contain jQuery, the follow error is shown:

> WebDriver\Exception\UnknownError: unknown error: jQuery is not defined

## Possible solution
The code is not difficult to do in vanilla js. Since it's used in two places, maybe have a private method to do this.
```php
    private function addHoverClass($id)
    {
        try {
            $this->getSession()->evaluateScript(
<<<"JS"
              const el = document.getElementById('$id');
              if (el) {
                const cl = el.className.split(' ');
                if (cl.indexOf('hover') === -1) {
                  cl.push('hover');
                  el.className = cl.join(' ');
                }
              }
JS
            );
        } catch (UnsupportedDriverActionException $e) {
            // This will fail for GoutteDriver but neither is it necessary.
        }
    }
```

## Steps to reproduce (for bugs)
1. Navigate to some page missing jQuery
2. Call `UserContext->iAmAnonymousUser()` (via `"And I log out"` statement)

## Context
Instead of seeing the actual error (eg; being logged out or ending up on a page without jQuery), this error is shown.

## Environment
- Behat 3, WordHat 2.0, PHP 7.1 (docker)

**Comment by paulgibbs** [comment]
Hi @uuf6429 

Thanks, yes, you're right!

**Comment by paulgibbs** [comment]
Swapped out!
