### ISSUE TITLE
Fix Kerning In Logo

### ISSUE THREAD

**Issue by BFTrick** [paulgibbs/behat-wordpress-extension#214]
## Current behaviour

The kerning on the logo isn't great. The space between the `W` and `o` is pretty bad and the spacing between the `a` and the `t`.

![wordhat_-_behat_for_wordpress](https://user-images.githubusercontent.com/1065372/44108822-b0df6554-9fb8-11e8-9547-372ff511750b.jpg)

## Possible solution

If you let me know what font you're using and how you styled the text I can try to fix it and submit a new version. :)

**Comment by paulgibbs** [comment]
I can't remember *where* it came from (one of those $10 for a logo service things) - I have it as a SVG: https://github.com/paulgibbs/behat-wordpress-extension/tree/master/docs/img

Open for any branding suggestions you can come up with. :)

**Comment by BFTrick** [comment]
![wordhat](https://user-images.githubusercontent.com/1065372/44155503-b7596972-a06a-11e8-8194-dc61a43f27d6.png)

This looks better. Want me to send a PR with the new SVG?

**Comment by paulgibbs** [comment]
Yes please!
