### ISSUE TITLE
Allow use of `page_template` in `ContentElement`

### ISSUE THREAD

**Issue by codereviewvideos** [paulgibbs/behat-wordpress-extension#239]
## Expected behaviour
When defining a Page via a Behat feature, I would like to be able to set a Page Template.

## Current behaviour
`page_template` is not in the whitelisted CLI args.

https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/Driver/Element/Wpcli/ContentElement.php#L49

## Possible solution
Add `page_template` to the white list.

## Steps to reproduce

```
  Background:
    Given there are pages:
      | slug   | title   | content      | status  | template                       |
      | slug-1 | My Page | content here | publish | page-templates/my-template.php |
```

## Context
Everything works as expected, but I cannot set the Page Template when creating new Pages in WordHat.

## Your environment
`"paulgibbs/behat-wordpress-extension": "^3.1",`

**Comment by paulgibbs** [comment]
This is going into 3.2.0, sorry it took so long to be released. Thanks again!
