### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by szepeviktor** [paulgibbs/behat-wordpress-extension#244]
Please see the output of `composer outdated`

Mainly WP-CLI v2

**Comment by paulgibbs** [comment]
Yep.

I also think it’s time to require the latest major WP CLI release (v2) as it came out in November last year I think, so I will change that as well.

**Comment by paulgibbs** [comment]
Done in #246!

**Comment by szepeviktor** [comment]
:)

**Comment by paulgibbs** [comment]
This is going into 3.2.0, sorry it took so long to be released. Thanks again!

**Comment by szepeviktor** [comment]
You're welcome.
