### ISSUE TITLE
Check the "Remember me" when logging in

### ISSUE THREAD

**Issue by johnbillion** [paulgibbs/behat-wordpress-extension#245]
## Expected behaviour
When using the `iAmLoggedInAsRole( ... )` step the user should remain logged in.

## Current behaviour
We're seeing some instances where the user's session expires part way through a feature, causing it to fail.

## Context
This appears to be caused by the fact the "Remember me" box isn't checked when logging in the user.

## Your environment
> Include as many relevant details about the environment you experienced the bug in:

* WordHat version used: 3.1.2
* Environment name and version: PHP 7.2 on Nginx
* Server operating system type and version: Chassis
* Type of Behat browser used (e.g. Selenium, headless Chrome, etc): selenium2

**Comment by paulgibbs** [comment]
Done in #247

**Comment by paulgibbs** [comment]
This is going into 3.2.0
