### ISSUE TITLE
Fetch Selenium Server via Composer

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#31]
I found https://github.com/joomla-projects/selenium-server-standalone which is a fork of https://github.com/sveneisenschmidt/selenium-server-standalone and it seems like the former is eventually going to merge back into the latter (the difference is some web driver support, but I'm not totally sure how useful that is, so I'm inclined to maybe perhaps use the latter for now).

I know not everyone will use Selenium but this removes a download/config step.

**Comment by stephenharris** [comment]
👍  - I prefer keeping dependencies in one central place. That said, we are only using it for our own tests. Would it be better to put it in as a `dev-dependancy`, and then in the documentation just suggest it's added as a dependancy (i.e. simply given an example `composer.json` here: https://wordhat.info/installation.html).

The reason for not including it as a `dependancy` is that we are then potentially tying the end-user to a specific version of Selenium. The problem with this is that Selenium and web drivers can often fall out of sync - so we'll probably need to be very specific about the version we use for Travis, and that might not work for everybody.

**Comment by paulgibbs** [comment]
👍

**Comment by paulgibbs** [comment]
Spent a couple of hours on this. Way harder than it seems. Different versions of Selenium compiled against different versions of Java, all sorts of incompatibilites/extra config needed for Travis-CI. I tried in a branch and gave up, we're not going to get enough benefit from this effort to spend more time on it (my time, at least).
