### ISSUE TITLE
Travis-CI build failures

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#38]
The "visiting the homepage" test scenario occasionally fails on Travis-CI with a "could not open connection" error.

## Expected behavior
That the test passes all the time.

## Current behavior
The test fails occasionally. No pattern has been observed yet.

It's been seen to fail on PHP 7.1 with `latest` WordPress on the `wpapi` driver.
 * https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/199566390

## Steps to reproduce (for bugs)
1. Trigger a Travis-CI build by making a new commit or submitting a pull request.

Let's use this ticket to log the failures so we can identify if they are random or if there is a pattern.

**Comment by paulgibbs** [comment]
PHP 7.1, latest, wpcli
* https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/199570383

PHP 5.6, nightly, wpcli
* https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/199570385

**Comment by stephenharris** [comment]
I've seen this issue before. It's always the first scenario so I think it's that selenium is not ready. If we re-add the `sleep 5` (or maybe 10, 15?) before running the tests we probably won't see this issue.

**Comment by paulgibbs** [comment]
Let's try.
