### ISSUE TITLE
Supporting custom drivers

### ISSUE THREAD

**Issue by stephenharris** [paulgibbs/behat-wordpress-extension#51]
## Expected behavior
For the end-user to be able to register a custom driver to use in the tests

## Current behavior

Only the default drivers are available.

Typically in plug-ins / themes / client- sites there will be a need to create custom steps specific to that project. Behat supports this by allowing users to specific the contexts they wish to use. Invariably, however, those step implementations will be need to interact with WordPress in a way that the native drivers do not support. For example, a step may want to make use of a plug-in/theme function.

## Possible solution
See #50 

## Context

For example, Event Organiser has the step `I have the following events:` - it is similar to the 'posts' equivalent provided by behat-wordpress-extension but it uses a custom function `eo_insert_event()`. It is currently not possible to (easily) add support for the invoking of that function the `wpapi` driver, or for the corresponding `wpcli` command to the `wpcli` driver.

**Comment by paulgibbs** [comment]
I am not against making it technically possible for 3rd party to add another driver. I'm just not sure how often support for custom drivers would be used.

For example:

> those step implementations will be need to interact with WordPress in a way that the native drivers do not support. For example, a step may want to make use of a plug-in/theme function.

* The WP-CLI driver can now call any WP-CLI command.
* The WP-API driver loads WordPress directly, so steps can already call whatever WordPress PHP they want.
* The blackbox driver is limited to interaction through a web browser, but even then someone could create a big step that goes into wp-admin, finds a plugin's settings screen, changes those settings, etc.

The Event Organiser examples... I still think are implementable within a custom context. Certainly for WP-CLI, and for WP-API, the PHP wouldn't be in the Driver class itself (a bit messy, but not terrible).

**Comment by paulgibbs** [comment]
Thinking a bit more, if it wasn't in a driver, your custom action would have to be hardcoded with the assumption that it'd be used for a particular driver i.e. `$this->getDriver()->wpcli( 'what', 'what' );` which might be fine in some circumstances

**Comment by stephenharris** [comment]
My thinking was that for the same reason we'd like to keep interaction with WP inside the driver for WordHat, it would be good to support that for the developer too.

That said, you're right - it's still possible for users to implement steps involving custom functions. I also agree that in most cases you will only need to use driver on any given project.

Let's close this now - and if the demand ever arises we can reconsider it at later point.
