### ISSUE TITLE
Add a REST API driver

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#52]
Consider adding a Driver that communicates with WordPress over the REST API.

## Current behavior
We have drivers that work over the browser, PHP, and WP-CLI. For sites that need remote configuration or set-up that can't use WP-CLI, we could use the REST API .

## Possible solution
Via Guzzle, or rmccue/requests.

**Comment by paulgibbs** [comment]
I think this is something that wouldn't hurt the project, but it is a relatively low priority. If someone is really excited about building this, go for it.

**Comment by paulgibbs** [comment]
Going to close this because I want #146 done before I get excited about adding a new driver (the easy bit).

**Comment by rvodden** [comment]
I should pull my finger out really - let me rebase my branch and see how far off #146 is :)
