### ISSUE TITLE
CI: take screenshots on failures, upload somewhere, post into Slack.

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#54]

**Comment by paulgibbs** [comment]
https://github.com/linusshops/behat-contexts/blob/master/src/LinusShops/Contexts/Web.php#L36 looks convenient to use to take the screenshots. That code is under MIT so we can re-use it without problem.

**Comment by stephenharris** [comment]
We'd need to upload the screenshots somewhere (AWS S3 or an image hosting service).

**Comment by paulgibbs** [comment]
Maybe avail ourselves of img.ur, or similar, or WordPress.com (either via REST API or post-by-email).

@stephenharris Since you mentioned this, do you want to take ownership of this and figure it out sometime?

**Comment by stephenharris** [comment]
Was thinking about this - would be good to have a record of the screenshots. But we probably don't want them spamming our Slack channel when someone (me) makes a silly mistake, and every one of our scenarios fail...

**Comment by paulgibbs** [comment]
right, maybe not, let's get them uploaded to somewhere sensible to start with and see how things go

**Comment by johnbillion** [comment]
There's a package for this: https://github.com/elvetemedve/behat-screenshot

I don't think this needs to be part of WordHat.

**Comment by paulgibbs** [comment]
Maybe not WordHat but I think there’s value in having it in the instance we run on Travis-CI because it’s so hard to debug tests there.

**Comment by rvodden** [comment]
Have we thought about using SauceLabs? Much like many of the other cloud tools its free for open source projects and would provide us with videos of all our tests for the last 30 days and screen shots at each step forever (ish). I'll spin up a branch to integrate our travis build with my SauceLabs account.

**Comment by ataylorme** [comment]
If you decide to do screenshots yourself consider using [Travis artifacts](https://docs.travis-ci.com/user/uploading-artifacts/) to help with storage.

**Comment by paulgibbs** [comment]
Now we have the Docker-based environment for Travis-CI runs, I don't think this is really needed.
