### ISSUE TITLE
Can't supply absolute file to `WpcliDriver::importDatabase`

### ISSUE THREAD

**Issue by stephenharris** [paulgibbs/behat-wordpress-extension#56]
## Expected behavior

I'm running tests on a remote machine using the `wp-cli` driver. I would like to reset the database after each scenario using a database dump file. 

## Current behavior
This is currently not possible. I can provide a path to the database dump, but it is assumed to be relative to the current working directory (on my local machine). The `wp-cli` command, for obvious reasons, can't import the file from my local computer. I need to instead provide an absolute path the the database dump on my remote machine.

Even when not running tests on a remote machine it would be useful to provide an absolute file path (e.g. I can use `%paths.base%` and this resolves to an absolute URL). 

## Possible solution
1. Make a breaking change and expect an absolute path. Users can use `%paths.base%` to provide a relative path (to their behat config).
2. Or make a partially (but sane) breaking change, and treat file paths with a forward slash as absolute paths.

## Steps to reproduce (for bugs)
1. In your context, :
```
	/**
	 * @BeforeScenario
	 */
	public function resetDatabase(BeforeScenarioScope $scope)
	{
		$this->getWordpress()->getDriver()->wpcli('db', 'reset',['--yes']);
		$this->getWordpress()->getDriver()->importDatabase('/absolute/path/to/dump.db');
	}
```
2. Run the tests
3. Watch it fail

## Your environment
* wp-cli driver
* Using a wp-cli alias to forward commands to a remote server.

**Comment by stephenharris** [comment]
I should point out, the use of `%paths.base%` is only available when you are suppling the path in your Behat config.

@paulgibbs Thoughts on 1 or 2. I vote 2.

**Comment by paulgibbs** [comment]
I vote for 2, too!
