### ISSUE TITLE
Provide (and use) commonly used helper functions

### ISSUE THREAD

**Issue by stephenharris** [paulgibbs/behat-wordpress-extension#58]
## Expected behaviour
In variably in contexts and page objects we need to use helper methods like `spin` and https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/PageObject/Element/AdminMenu.php#L101

We don't want to repeat such methods in class that we use them, so it would be helpful to store this in a class-agnostic way. Either as Trait or a function. (I don't see any advantage in the latter over the former in this instance, so I would suggest using functions).

Then any class (context, page/element object or otherwise) can use, for instance `Util/spin( \Closure)`.

To be clear these helper functions do not include step definitions. 

## Current behaviour
The closest thing we have to reusable code is the `spin` method in `RawWordpressContext`. This is less than ideal because it requires classes that wish to use it to extend `RawWordpressContext` (not always possible or desirable)

## Possible solution
1. Define these methods as functions in `Util` namespace. 
2. We could put these functions in a separate package, making them available to the wider community. 

## Context

I need to use the `spin` method in a page object. Currently I have to copy and paste the spin method to the page object.

## Your environment
n/a

**Comment by paulgibbs** [comment]
I think this is done? For now?
