### ISSUE TITLE
Log-out step fails

### ISSUE THREAD

**Issue by stephenharris** [paulgibbs/behat-wordpress-extension#65]
## Expected behaviour

This should pass:

```
@javascript
Scenario
Given I am logged in as an admin
And I am on the Dashboard 
Then I should see "Howdy"
Given I am an anonymous user
Then I should not see "Howdy"
```

## Current behavior

It fails as the step `Given I am an anonymous user` with the following message:

> Element is not currently visible and so may not be interacted with

It passes when not using `@javascript`

## Possible solution
The element `#wp-admin-bar-logout` is not visible, you need to hover over the "Howdy...". However

```
$page->find('css','#wp-admin-bar-my-account')->mouseOver();
```

does not work, because WordPress is using HoverIntent: https://github.com/WordPress/WordPress/blob/dd6da701b286579819cd6aa518aa2d7018efd759/wp-includes/js/admin-bar.js

Potentially we can use JS to add the class `hover` (the step works fine without JS).

## Steps to reproduce (for bugs)
See Scenario above

## Context
Trying to log-out after logging in

**Comment by paulgibbs** [comment]
Good find

**Comment by paulgibbs** [comment]
Link to `/wp-login.php?action=logout` directly?

**Comment by stevector** [comment]
> Link to `/wp-login.php?action=logout` directly?

I think that's a safe route. The Drupal extension does the same thing for its logout step.

https://github.com/jhedstrom/drupalextension/blob/v3.2.2/src/Drupal/DrupalExtension/Context/RawDrupalContext.php#L488
https://github.com/jhedstrom/drupalextension/blob/v3.2.2/src/Drupal/DrupalExtension/Context/DrupalContext.php#L24

**Comment by stephenharris** [comment]
If the log-out URL has changed this will not work. 

For example the client I'm working for we have single sign in/out via SAML and the logout URL is different.

As an aside, I have a working fox for this which will also be relevant for other toolbar interactions (clicking New > Posts, for example).

Happy to do either but using the toolbar more closely reflects user behaviour.

**Comment by paulgibbs** [comment]
I think it's really important that as many step definitions as possible do not require JS, unless WP itself requires it (i.e. Customizer). Especially so for basic things like log-in/out.

**Comment by stevector** [comment]
> For example the client I'm working for we have single sign in/out via SAML and the logout URL is different.

Could the plugin redirect the normal log out link to the custom one?

Pantheon's SAML plugin overrides the login form but redirects from the normal login url. We still do have to override the Behat login step from our shared test suite to accommodate the different form fields used by the SAML plugin.

See https://github.com/pantheon-systems/wp-saml-auth/blob/master/tests/behat/bootstrap/AdminLogIn.php#L26 and
https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests/blob/master/features/bootstrap/AdminLogIn.php#L26

> Happy to do either but using the toolbar more closely reflects user behaviour.

I expect there will be many steps where there's a tension between following the user behaviour as closely as possible (clicking the toolbar link) and a more reliable execution (going directly to the logout URL). I lean toward the more reliable execution.

**Comment by stephenharris** [comment]
@stevector  Actually it does. But accessing `/wp-login.php?action=logout` doesn't work because it requires a nonce. I had mistakenly assumed that wasn't WordPress functionality - but it is.

So in short, we can use  `/wp-login.php?action=logout` but we'd just need to click the confirmation link on the 'Are you sure?' page.

**Comment by stephenharris** [comment]
@paulgibbs  Just to clarify, nothing requires a JS-enabled driver. It's just a fallback for such drivers, similiar to: https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/PageObject/Element/AdminMenu.php#L66-L72

**Comment by paulgibbs** [comment]
Urgh, nonces.

Well, if it's easy to pop the Howdy menu down, that sounds less hacky.
