### ISSUE TITLE
Links / Buttons behind the wp-admin bar are inaccessible

### ISSUE THREAD

**Issue by stephenharris** [paulgibbs/behat-wordpress-extension#81]
## Expected behavior
When telling Behat to click or press, or otherwise interact with an item it shouldn't throw a strop when that item is sitting underneath the admin bar. 

## Current behavior
It throws a strop. Specifically, Selenium complains:

> Element is not clickable at point (577.0999755859375, 8.75). Other element would receive the click: `<div id="wpadminbar" class=""></div>`

Here's a screenshot demonstrating the problem: 

![50mbsample-10](https://cloud.githubusercontent.com/assets/3255034/24961966/58d2869a-1f92-11e7-8ca8-e9fcb27673f9.png)

## Possible solution

This is a workable solution. It uses JavaScript to replace the toolbar's 'fixed' position with an 'absolute' one, keeping at the top of the page. In some instances, some positioning is required to address the padding on `html.wp-toolbar` to ensure the toolbar sits at the top of the page, not a little way down.

```
/**
 * @BeforeStep
 */
public function beforeStep(BeforeStepScope $scope)
{
	if ($this->getSession()->getDriver() instanceof \Behat\Mink\Driver\Selenium2Driver) {
		if ( $this->getSession()->getDriver()->getWebDriverSession() ) {
			$this->getSession()->getDriver()->executeScript(
				'if (document.getElementById("wpadminbar")){
					document.getElementById("wpadminbar").style.position="absolute";
					if ( document.getElementsByTagName("body")[0].className.match(/wp-admin/) ) {
						document.getElementById("wpadminbar").style.top="-32px";
					}
				};'
			);
		}
	}
}
```

## Steps to reproduce (for bugs)

I believe if you're trying to access an item above the viewport Selenium will scroll up enough for it to be on the screen, but it will then be behind the admin bar.

**Comment by paulgibbs** [comment]
This problem doesn't exist with non-JS?

**Comment by stephenharris** [comment]
No - it's a JS only issue. GoutteDriver can see everything (even things which are hidden to the user)

**Comment by paulgibbs** [comment]
in that case i am all for a workaround like what you've done. Just... reformat that code sample and don't nest all those IFs ;)

**Comment by stephenharris** [comment]
If statements are a work of art ;)
