### ISSUE TITLE
"Accessing WordPress site" test fails when WP is served from a subdirectory.

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#83]
The "Accessing WordPress site" test, which checks for "/readme.html", fails if the WP files are in a subdirectory (i.e. home_url and site_url are different).

## Expected behaviour
The test passes in all configurations.

## Current behaviour
It fails when the WordPress site has different home_url and site_url values.

## Possible solution
Re-implement Mink's `Given I am on` method and add the WP path prefix if a leading slash is found. We do something similar already, I believe, in RawWordpressContext's `locatePath` method.

## Context
Trying to pass tests on local dev. env.

## Your environment
* Using https://chassis.io/ for WP dev. env.

**Comment by stephenharris** [comment]
I don't think this needs fixing. If I'm an end user and I want to test the readme file exists in subdirectory install of WordPress then I would just use the step:

     Given I am on "subdir/readme.html"


> The test passes in all configurations

Our tests (`.feature` files) need only pass in our configuration - in this case, WordPress installed at root. It's a valid question to ask whether WordHat will still work for WordPress in a subdirectory (I *think* it does, and it should) but we would need a whole parallel suite of tests which reflect that set-up. The fact that this is a right PITA is a reflection of the fact that we are testing backwards: we are essentially running an site which we assume is working correctly, and then running our tests to check they pass (we have no negative path tests).

I guess my point is the tests are failing correctly: you asked for a readme file at the root of your site and it did not exist. It's not WordHat that's broken, it's the `.feature` file has the wrong expectation.

**Comment by paulgibbs** [comment]
Well, it does need fixing -- or the test removing. It irritates me with a failure every time I run the whole test suite.

My WordHat dev env does not have WordPress installed at the route. This is intention, to ensure what we write works on the variety of WordPress configurations. It's proved helpful in the early days, which is why we have that option site_url configuration var in the yml now. :)

**Comment by stephenharris** [comment]
I think it can be removed - its only purpose was to check that we had the install set-up - I think its served its purpose, and the other tests will soon tell us if anything falls over.

**Comment by paulgibbs** [comment]
Sure, I'll pull it out. :)

**Comment by paulgibbs** [comment]
Done.
