### ISSUE TITLE
Should we clean content between tests?

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#90]
A good amount of Behat tests that test the interface will create, update, or delete content.
The WP-API driver has support for MySQL transactions (though probably not 100% implemented yet, I haven't tested it in a while), the WP-CLI driver has support for SQL dump import/export.

The Drupal Behat Extension I think has similar options, but it also keeps track of data created, so it knows what to tidy up with an `AfterScenario` hook.

I found a blog post explaining the basics quite well: https://www.metaltoad.com/blog/what-i-learned-today-drupal-behat-scenario-cleanup

> The way the Drupal Behat extension works, it tracks nodes, users, roles and taxonomy terms you create using its methods, so that in its @AfterScenario function knows which nodes to delete. 

Let's discuss how we see Behat being used with WordPress, and review our current approaches, and consider if something like the above would be a desirable feature to implement for a future major release.

**Comment by stephenharris** [comment]
What about content thats updated, or deleted as part of the test? 

Is it possible to simply take a snapshot of the database and restore that after the test is run (I think it must be... certainly restoring a database dump is....)? That does then beg the question, what else should we be cleaning up? Uploads? Plugins /Themes installed?

I think trying to catch individual changes to later 'roll back' would be too difficult and liable to miss stuff, particular changes to custom tables. So perhaps we could just incorporate into a WordHat a tag in which we take a database snapshot at `@beforeScenario` which is then restored at `@afterScenario`. Perhaps an additional tag for the uploads directory (?).

Either way, this reset should be optional: WordHat can currently be used for smoke testing on a live site.

**Comment by paulgibbs** [comment]
> What about content thats updated, or deleted as part of the test?

I think the general idea i've seen is it keeps track of IDs internally somewhere and pops/pulls from them as items get removed/added.

**Comment by paulgibbs** [comment]
@stephenharris and I discussed this in-person at WCEU today.

We've decided to add a parameter that if set, will:

* Back up the database via BeforeSuite
* Restore the database via AfterScenario...
* ...unless said scenario has a tag that means "I didn't mess with the database".

We are not overly concerned about the creation of a backup causing time-outs or memory exhaustion (particular for the PHP Driver). These'll only scale so far, and the WP-CLI driver should do this well enough for all but the largest databases (famous last words...).
 
This'll complement the existing CLI-only DB transactions. I think we might end up calling these "rollbacks" on the website's feature list.

**Comment by stephenharris** [comment]
Just to add it would be good if there's an option to support a pre-existing mysql dump. E.g. an option such as `rollback:` which accepts `auto` or `path/to/mysql/dump.sql`

**Comment by paulgibbs** [comment]
I am beginning to work on this.

@stephenharris Did we discuss, if we generate a backup in BeforeSuite, do we delete it in AfterSuite (or some event)? Otherwise it could be possible to develop this so that the next run would find that backup and use it.

I am not sure this is a great idea because we've magically changed the behaviour under the hood and I could see someone not realising and getting annoyed debugging why some expected change isn't working.

**Comment by stephenharris** [comment]
Do we need to? If `BeforeSuite` is making a database dump then it'll over-ride any existing file...

From a usability point of view it would be helpful if it *didn't* restore the old dump: I may have spent some time getting the install 'set up' for the tests, only to find running the tests wipes that away. So I'd advocate taking a fresh 'snapshot' each time the tests are run.

**Comment by paulgibbs** [comment]
I've merged the first go at this into Master. I've tested WP-CLI more than WP-PHP at this point, and so far so good.
